# Generated by Django 3.0.4 on 2020-03-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200330_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macdhcp',
            name='dns_name',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='ip_add',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='ip_switch',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='lastupd',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='port',
        ),
        migrations.RemoveField(
            model_name='macdhcp',
            name='vlan',
        ),
    ]
