# Generated by Django 3.0.4 on 2020-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200331_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switches',
            options={'ordering': ['ip_switch'], 'verbose_name': 'Коммутатор', 'verbose_name_plural': 'Коммутаторы'},
        ),
    ]
