# Generated by Django 3.0.4 on 2020-04-09 11:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200331_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='swmodels',
            name='url',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
