# Generated by Django 3.0.4 on 2020-04-09 11:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_swmodels_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swmodels',
            name='url',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
